import React, { useState } from "react";
import { useGeneratePitchDeckMutation, useGenerateFreePitchDeckMutation } from "../../redux/apis/ai.model.api";
import toast from "react-hot-toast";

interface IPitchDeckData {
  logline: string;
  synopsis: string;
  genre: string;
  tone: string;
  comparableTitles: string[];
  themes: string[];
  targetAudience: string;
  characters: { name: string; role: string; arc: string }[];
  worldBuilding: string;
  seriesPotential: string;
}

interface StoryPitchDeckProps {
  title: string;
  content: string;
  tag: string;
  isLogin: boolean;
  onClose: () => void;
}

const StoryPitchDeck: React.FC<StoryPitchDeckProps> = ({
  title,
  content,
  tag,
  isLogin,
  onClose,
}) => {
  const [pitchData, setPitchData] = useState<IPitchDeckData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatePitchDeck] = useGeneratePitchDeckMutation();
  const [generateFreePitchDeck] = useGenerateFreePitchDeckMutation();

  const handleGenerate = async () => {
    setIsGenerating(true);
    const toastId = toast.loading("Generating your pitch deck...");
    try {
      const payload = { title, content, tag };
      const res = isLogin
        ? await generatePitchDeck(payload).unwrap()
        : await generateFreePitchDeck(payload).unwrap();
      setPitchData(res.data ?? res);
      toast.success("Pitch deck generated!", { id: toastId });
    } catch {
      toast.error("Failed to generate pitch deck.", { id: toastId });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportPDF = async () => {
    if (!pitchData) return;
    const toastId = toast.loading("Exporting PDF...");
    try {
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const lm = 20, rm = 20, tm = 20;
      const pw = 210 - lm - rm;
      let y = tm;

      // Header
      doc.setFillColor(99, 102, 241);
      doc.rect(0, 0, 210, 40, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text(title, lm, 18);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("STORY PITCH DECK — Generated by StorySparkAI", lm, 28);
      doc.text(pitchData.genre.toUpperCase(), 190, 28, { align: "right" });
      y = 50;

      const addSection = (heading: string, body: string) => {
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(99, 102, 241);
        doc.text(heading.toUpperCase(), lm, y);
        y += 6;
        doc.setDrawColor(99, 102, 241);
        doc.setLineWidth(0.3);
        doc.line(lm, y, 190, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(30, 41, 59);
        const lines = doc.splitTextToSize(body, pw);
        lines.forEach((line: string) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(line, lm, y);
          y += 5.5;
        });
        y += 4;
      };

      addSection("Logline", pitchData.logline);
      addSection("Synopsis", pitchData.synopsis);
      addSection("Genre & Tone", `Genre: ${pitchData.genre}\nTone: ${pitchData.tone}`);
      addSection("Comparable Titles", pitchData.comparableTitles.join(" • "));
      addSection("Themes", pitchData.themes.join(" • "));
      addSection("Target Audience", pitchData.targetAudience);
      addSection("World Building", pitchData.worldBuilding);
      addSection("Series Potential", pitchData.seriesPotential);

      if (pitchData.characters.length > 0) {
        if (y > 240) { doc.addPage(); y = 20; }
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(99, 102, 241);
        doc.text("CHARACTERS", lm, y);
        y += 6;
        doc.setDrawColor(99, 102, 241);
        doc.setLineWidth(0.3);
        doc.line(lm, y, 190, y);
        y += 5;
        pitchData.characters.forEach((char) => {
          if (y > 265) { doc.addPage(); y = 20; }
          doc.setFont("helvetica", "bold");
          doc.setFontSize(10);
          doc.setTextColor(30, 41, 59);
          doc.text(`${char.name} — ${char.role}`, lm, y);
          y += 5;
          doc.setFont("helvetica", "normal");
          const arcLines = doc.splitTextToSize(`Arc: ${char.arc}`, pw);
          arcLines.forEach((line: string) => {
            if (y > 270) { doc.addPage(); y = 20; }
            doc.text(line, lm + 4, y);
            y += 5;
          });
          y += 2;
        });
      }

      // Footer
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text("Generated with StorySparkAI", lm, 290);
        doc.text(`Page ${i} of ${totalPages}`, 190, 290, { align: "right" });
      }

      const safeTitle = title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
      doc.save(`${safeTitle}_pitch_deck.pdf`);
      toast.success("PDF downloaded!", { id: toastId });
    } catch {
      toast.error("Failed to export PDF.", { id: toastId });
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto border border-slate-200 dark:border-slate-700">
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between p-6 border-b border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 rounded-t-2xl">
          <div>
            <h2 className="text-xl font-extrabold text-slate-900 dark:text-white">📋 Story Pitch Deck</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Netflix-style story bible for <span className="font-semibold">{title}</span></p>
          </div>
          <div className="flex items-center gap-2">
            {pitchData && (
              <button
                onClick={handleExportPDF}
                className="rounded-xl px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold uppercase tracking-wider transition-all"
              >
                📄 Export PDF
              </button>
            )}
            <button
              onClick={onClose}
              className="rounded-xl px-4 py-2 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 text-xs font-bold uppercase tracking-wider transition-all hover:bg-slate-200 dark:hover:bg-slate-700"
            >
              ✕ Close
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {!pitchData && !isGenerating && (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <div className="text-6xl mb-4">🎬</div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">Generate Your Pitch Deck</h3>
              <p className="text-sm text-slate-500 dark:text-slate-400 max-w-md mb-6">
                Transform your story into a professional Netflix-style pitch document with logline, synopsis, character breakdowns, and more.
              </p>
              <button
                onClick={handleGenerate}
                className="rounded-xl px-8 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold text-sm uppercase tracking-wider shadow-lg transition-all hover:scale-105"
              >
                ✨ Generate Pitch Deck
              </button>
            </div>
          )}

          {isGenerating && (
            <div className="flex flex-col items-center justify-center py-16">
              <div className="animate-spin rounded-full h-12 w-12 border-2 border-slate-300 border-t-indigo-600 mb-4"></div>
              <p className="text-sm font-bold uppercase tracking-wider text-slate-400 animate-pulse">Analyzing story structure...</p>
            </div>
          )}

          {pitchData && (
            <div className="space-y-6">
              {/* Logline */}
              <div className="p-5 bg-gradient-to-r from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 rounded-xl">
                <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 mb-2">📌 Logline</h3>
                <p className="text-slate-800 dark:text-slate-200 font-semibold italic text-base leading-relaxed">"{pitchData.logline}"</p>
              </div>

              {/* Genre & Tone */}
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">🎭 Genre</h3>
                  <p className="text-slate-800 dark:text-slate-200 font-semibold text-sm">{pitchData.genre}</p>
                </div>
                <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">🎨 Tone</h3>
                  <p className="text-slate-800 dark:text-slate-200 font-semibold text-sm">{pitchData.tone}</p>
                </div>
              </div>

              {/* Synopsis */}
              <div className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">📖 Synopsis</h3>
                <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed whitespace-pre-line">{pitchData.synopsis}</p>
              </div>

              {/* Comparable Titles */}
              <div className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">🎬 Comparable Titles</h3>
                <div className="flex flex-wrap gap-2">
                  {pitchData.comparableTitles.map((t, i) => (
                    <span key={i} className="px-3 py-1.5 bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20 rounded-full text-xs font-bold">{t}</span>
                  ))}
                </div>
              </div>

              {/* Themes */}
              <div className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">💡 Themes</h3>
                <div className="flex flex-wrap gap-2">
                  {pitchData.themes.map((theme, i) => (
                    <span key={i} className="px-3 py-1.5 bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20 rounded-full text-xs font-bold">{theme}</span>
                  ))}
                </div>
              </div>

              {/* Target Audience */}
              <div className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">👥 Target Audience</h3>
                <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">{pitchData.targetAudience}</p>
              </div>

              {/* Characters */}
              <div className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">👤 Characters</h3>
                <div className="space-y-3">
                  {pitchData.characters.map((char, i) => (
                    <div key={i} className="p-3 bg-white dark:bg-slate-900/60 rounded-lg border border-slate-200 dark:border-slate-700">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-bold text-slate-900 dark:text-white text-sm">{char.name}</span>
                        <span className="text-xs px-2 py-0.5 bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 rounded-full font-medium">{char.role}</span>
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{char.arc}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* World Building */}
              <div className="p-5 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-200 dark:border-slate-700">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">🌍 World Building</h3>
                <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">{pitchData.worldBuilding}</p>
              </div>

              {/* Series Potential */}
              <div className="p-5 bg-gradient-to-r from-emerald-500/10 to-teal-500/10 border border-emerald-500/20 rounded-xl">
                <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400 mb-2">🚀 Series Potential</h3>
                <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">{pitchData.seriesPotential}</p>
              </div>

              {/* Regenerate */}
              <div className="flex justify-center pt-2">
                <button
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  className="rounded-xl px-6 py-2.5 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 text-xs font-bold uppercase tracking-wider transition-all hover:bg-slate-200 dark:hover:bg-slate-700"
                >
                  🔄 Regenerate
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default StoryPitchDeck;